// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvyublznngrcsrrqyrha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2eXVibHpubmdyY3NycnF5cmhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzQzMjEsImV4cCI6MjA2MTExMDMyMX0.gx47-LqzGvs_j2vS6JpWGLwhnbgNZHS_RxZq6_gFGew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);